"""
Snowflake Feature Store Bridge
===============================

Python backend for snowflakeR::R/features.R.

This module wraps the snowflake.ml.feature_store Python API, providing
functions callable from R via reticulate. Each function receives a Snowpark
session object (from the sfr_connection) and performs Feature Store operations.

Key design decisions:
  - All pandas DataFrames returned to R are automatically converted by
    reticulate; no manual conversion needed.
  - The FeatureStore object is instantiated per-call or cached in the R-side
    connection object to avoid stale references.
  - FeatureView source data is passed as SQL strings from R (generated by
    dbplyr or written manually), then wrapped in session.sql().
"""

from typing import Dict, List, Optional, Any


# =============================================================================
# Internal helpers
# =============================================================================

def _get_feature_store(
    session,
    database: str,
    schema: str,
    default_warehouse: str,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
):
    """
    Get or create a FeatureStore instance.

    Args:
        session: Active Snowpark Session.
        database: Database containing the Feature Store schema.
        schema: Schema name for the Feature Store.
        default_warehouse: Default warehouse for compute.
        creation_mode: "CREATE_IF_NOT_EXIST" or "FAIL_IF_NOT_EXIST".

    Returns:
        FeatureStore instance.
    """
    from snowflake.ml.feature_store import FeatureStore, CreationMode

    mode_map = {
        "CREATE_IF_NOT_EXIST": CreationMode.CREATE_IF_NOT_EXIST,
        "FAIL_IF_NOT_EXIST": CreationMode.FAIL_IF_NOT_EXIST,
    }
    mode = mode_map.get(creation_mode, CreationMode.FAIL_IF_NOT_EXIST)

    return FeatureStore(
        session=session,
        database=database,
        name=schema,
        default_warehouse=default_warehouse,
        creation_mode=mode,
    )


def _make_entity(name: str, join_keys: List[str], desc: Optional[str] = None):
    """Create a local (draft) Entity object."""
    from snowflake.ml.feature_store import Entity
    return Entity(name=name, join_keys=join_keys, desc=desc or "")


def _make_feature_view(
    session,
    name: str,
    entities: list,
    sql: str,
    refresh_freq: Optional[str] = None,
    warehouse: Optional[str] = None,
    timestamp_col: Optional[str] = None,
    desc: Optional[str] = None,
):
    """
    Create a local (draft) FeatureView object.

    Args:
        session: Active Snowpark Session.
        name: FeatureView name.
        entities: List of Entity objects.
        sql: SQL query defining the feature transformation.
        refresh_freq: Refresh frequency string (e.g., "1 hour") or None.
        warehouse: Override warehouse for this FeatureView.
        timestamp_col: Timestamp column name for time-series features.
        desc: Description.

    Returns:
        A draft FeatureView object.
    """
    from snowflake.ml.feature_store import FeatureView

    feature_df = session.sql(sql)

    fv = FeatureView(
        name=name,
        entities=entities,
        feature_df=feature_df,
        refresh_freq=refresh_freq,
        timestamp_col=timestamp_col,
        desc=desc or "",
        warehouse=warehouse,
    )

    return fv


# =============================================================================
# Entity operations
# =============================================================================

def register_entity(
    session,
    name: str,
    join_keys: List[str],
    desc: Optional[str] = None,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "CREATE_IF_NOT_EXIST",
) -> Dict[str, Any]:
    """
    Create and register an entity in the Feature Store.

    Args:
        session: Active Snowpark Session.
        name: Entity name.
        join_keys: List of join key column names.
        desc: Entity description.
        database: Feature Store database.
        schema: Feature Store schema.
        warehouse: Default warehouse.
        creation_mode: "CREATE_IF_NOT_EXIST" or "FAIL_IF_NOT_EXIST".

    Returns:
        Dict with entity info (name, join_keys, desc).
    """
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    entity = _make_entity(name, join_keys, desc)
    registered = fs.register_entity(entity)

    return {
        "name": registered.name if hasattr(registered, 'name') else name,
        "join_keys": join_keys,
        "desc": desc or "",
    }


def get_entity(
    session,
    name: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
) -> Dict[str, Any]:
    """Retrieve a registered entity by name."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh)
    entity = fs.get_entity(name)

    return {
        "name": entity.name,
        "join_keys": list(entity.join_keys),
        "desc": getattr(entity, 'desc', ''),
    }


def list_entities(
    session,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
) -> Any:
    """List all entities in the Feature Store. Returns a pandas DataFrame."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh)
    return fs.list_entities().to_pandas()


def delete_entity(
    session,
    name: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
) -> None:
    """Delete an entity by name."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh)
    fs.delete_entity(name)


# =============================================================================
# Feature View operations
# =============================================================================

def register_feature_view(
    session,
    name: str,
    version: str,
    sql: str,
    entity_names: List[str],
    entity_join_keys: Optional[List[List[str]]] = None,
    refresh_freq: Optional[str] = None,
    warehouse: Optional[str] = None,
    timestamp_col: Optional[str] = None,
    desc: Optional[str] = None,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    overwrite: bool = False,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> Dict[str, Any]:
    """
    Register a Feature View in the Snowflake Feature Store.

    Entities must already be registered. This function:
    1. Connects to the Feature Store.
    2. Retrieves the named entities.
    3. Creates a draft FeatureView from the SQL + entities.
    4. Registers (materialises) the FeatureView.

    Args:
        session: Active Snowpark Session.
        name: FeatureView name.
        version: Version string (e.g., "v1").
        sql: SQL defining the feature transformation.
        entity_names: List of registered entity names.
        entity_join_keys: Not used when entities are pre-registered.
        refresh_freq: Refresh frequency (e.g., "1 hour", "0 30 * * *").
        warehouse: Warehouse override.
        timestamp_col: Timestamp column for time-series features.
        desc: Description.
        database: Feature Store database.
        schema: Feature Store schema.
        overwrite: If True, overwrite existing version.
        creation_mode: FeatureStore creation mode.

    Returns:
        Dict with registered FeatureView info.
    """
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)

    # Retrieve registered entities
    entities = [fs.get_entity(en) for en in entity_names]

    # Create draft FeatureView
    fv = _make_feature_view(
        session=session,
        name=name,
        entities=entities,
        sql=sql,
        refresh_freq=refresh_freq,
        warehouse=wh,
        timestamp_col=timestamp_col,
        desc=desc,
    )

    # Register (materialise)
    registered_fv = fs.register_feature_view(
        feature_view=fv,
        version=version,
        overwrite=overwrite,
    )

    return {
        "name": registered_fv.name,
        "version": registered_fv.version,
        "status": str(registered_fv.status),
        "desc": getattr(registered_fv, 'desc', desc or ''),
    }


def get_feature_view(
    session,
    name: str,
    version: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
) -> Dict[str, Any]:
    """Retrieve a registered FeatureView by name and version."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh)
    fv = fs.get_feature_view(name, version)

    return {
        "name": fv.name,
        "version": fv.version,
        "status": str(fv.status),
        "desc": getattr(fv, 'desc', ''),
        "timestamp_col": getattr(fv, 'timestamp_col', None),
        "_py_fv": fv,  # Keep Python object for downstream use
    }


def list_feature_views(
    session,
    entity_name: Optional[str] = None,
    feature_view_name: Optional[str] = None,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
) -> Any:
    """List Feature Views. Returns a pandas DataFrame."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh)
    kwargs = {}
    if entity_name:
        kwargs["entity_name"] = entity_name
    if feature_view_name:
        kwargs["feature_view_name"] = feature_view_name

    return fs.list_feature_views(**kwargs).to_pandas()


def delete_feature_view(
    session,
    name: str,
    version: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
) -> None:
    """Delete a registered FeatureView."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh)
    fs.delete_feature_view(name, version)


def refresh_feature_view(
    session,
    name: str,
    version: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
) -> None:
    """Manually refresh a FeatureView."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh)
    fs.refresh_feature_view(name, version)


def read_feature_view(
    session,
    name: str,
    version: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
) -> Any:
    """Read data from a registered FeatureView. Returns pandas DataFrame."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh)
    return fs.read_feature_view(name, version).to_pandas()


def suspend_feature_view(
    session,
    name: str,
    version: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
) -> None:
    """Suspend a FeatureView's automatic refresh."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh)
    fs.suspend_feature_view(name, version)


def resume_feature_view(
    session,
    name: str,
    version: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
) -> None:
    """Resume a suspended FeatureView's automatic refresh."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh)
    fs.resume_feature_view(name, version)


# =============================================================================
# Training data generation
# =============================================================================

def generate_training_set(
    session,
    spine_sql: str,
    feature_view_refs: List[Dict[str, str]],
    spine_timestamp_col: Optional[str] = None,
    spine_label_cols: Optional[List[str]] = None,
    save_as: Optional[str] = None,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
) -> Any:
    """
    Generate a training set by joining spine data with Feature Views.

    Args:
        session: Active Snowpark Session.
        spine_sql: SQL query or table name for the spine (label) data.
        feature_view_refs: List of dicts with "name" and "version" keys.
        spine_timestamp_col: Timestamp column in spine for PIT joins.
        spine_label_cols: Label column names in spine.
        save_as: Optional table name to materialise results.
        database: Feature Store database.
        schema: Feature Store schema.
        warehouse: Default warehouse.

    Returns:
        pandas DataFrame with the training data.
    """
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh)

    # Build spine DataFrame
    spine_df = session.sql(spine_sql)

    # Retrieve registered FeatureViews
    fvs = []
    for ref in feature_view_refs:
        fv = fs.get_feature_view(ref["name"], ref["version"])
        fvs.append(fv)

    kwargs = {}
    if spine_timestamp_col:
        kwargs["spine_timestamp_col"] = spine_timestamp_col
    if spine_label_cols:
        kwargs["spine_label_cols"] = spine_label_cols
    if save_as:
        kwargs["save_as"] = save_as

    result_df = fs.generate_training_set(
        spine_df=spine_df,
        features=fvs,
        **kwargs,
    )

    return result_df.to_pandas()


def retrieve_features(
    session,
    spine_sql: str,
    feature_view_refs: List[Dict[str, str]],
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
) -> Any:
    """
    Retrieve feature values for inference (no labels, no PIT).

    Args:
        session: Active Snowpark Session.
        spine_sql: SQL for entity key values.
        feature_view_refs: List of dicts with "name" and "version" keys.
        database: Feature Store database.
        schema: Feature Store schema.
        warehouse: Default warehouse.

    Returns:
        pandas DataFrame with feature values.
    """
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh)

    spine_df = session.sql(spine_sql)
    fvs = [fs.get_feature_view(ref["name"], ref["version"]) for ref in feature_view_refs]

    result_df = fs.generate_training_set(
        spine_df=spine_df,
        features=fvs,
    )

    return result_df.to_pandas()


# =============================================================================
# Additional operations
# =============================================================================

def update_entity(
    session,
    name: str,
    desc: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
) -> None:
    """Update an entity's description."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh)
    entity = fs.get_entity(name)
    fs.update_entity(name, desc=desc)


def get_refresh_history(
    session,
    name: str,
    version: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    verbose: bool = False,
) -> Any:
    """Get refresh history for a Feature View. Returns pandas DataFrame."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh)
    return fs.get_refresh_history(name, version, verbose=verbose).to_pandas()


def setup_feature_store_schema(
    session,
    database: str,
    schema: str,
    warehouse: str,
) -> None:
    """
    Set up the Feature Store schema and required objects.

    Calls the standalone setup_feature_store() helper from snowflake.ml.
    """
    from snowflake.ml.feature_store import setup_feature_store

    setup_feature_store(
        session=session,
        database=database,
        schema=schema,
        warehouse=warehouse,
    )
