# ============================================================================
# Test Script: DuckDB Iceberg Integration with Snowflake Horizon Catalog
# ============================================================================
# This script tests querying Snowflake-managed Iceberg tables via DuckDB's
# iceberg extension using the Horizon Catalog REST API.
#
# Prerequisites:
# - DuckDB R package installed
# - Access token for Horizon Catalog (generated via JWT)
# - NATION_ICEBERG table exists in SIMON.PUBLIC
# ============================================================================

library(DBI)
library(duckdb)

cat("=== DuckDB Iceberg Integration Test ===\n\n")

# Configuration
ACCOUNT <- "SFPRODUCTSTRATEGY-AK32940"
DATABASE <- "SIMON"
SCHEMA <- "PUBLIC"
TABLE <- "NATION_ICEBERG"
ROLE <- "SYSADMIN"

# Horizon Catalog endpoint
CATALOG_ENDPOINT <- paste0("https://", ACCOUNT, ".snowflakecomputing.com/polaris/api/catalog")
cat("Catalog Endpoint:", CATALOG_ENDPOINT, "\n\n")

# Connect to DuckDB
con <- dbConnect(duckdb())
cat("DuckDB connection established\n")

# Install and load iceberg extension
cat("Loading iceberg extension...\n")
dbExecute(con, "INSTALL iceberg")
dbExecute(con, "LOAD iceberg")
cat("Iceberg extension loaded\n\n")

# Read access token from file (generated by Python script)
token_file <- "/tmp/horizon_access_token.txt"
if (file.exists(token_file)) {
    ACCESS_TOKEN <- trimws(readLines(token_file, n = 1))
    cat("Access token loaded (length:", nchar(ACCESS_TOKEN), ")\n\n")
} else {
    # If no token file, try to generate one using Python
    cat("No cached token found, generating new token...\n")
    system2("python3", args = c("-c", paste0('
import jwt
import time
import hashlib
import base64
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.backends import default_backend
import requests
import os

ACCOUNT = "SFPRODUCTSTRATEGY-AK32940"
USER = "SIMON"
ROLE = "SYSADMIN"

key_path = os.path.expanduser("~/.snowflake/keys/simon_rsa_key.p8")
with open(key_path, "rb") as key_file:
    private_key = serialization.load_pem_private_key(
        key_file.read(), password=None, backend=default_backend()
    )

public_key = private_key.public_key()
public_key_bytes = public_key.public_bytes(
    encoding=serialization.Encoding.DER,
    format=serialization.PublicFormat.SubjectPublicKeyInfo
)
sha256_hash = hashlib.sha256(public_key_bytes).digest()
fingerprint = "SHA256:" + base64.standard_b64encode(sha256_hash).decode("utf-8")

now = int(time.time())
payload = {
    "iss": f"{ACCOUNT}.{USER}.{fingerprint}",
    "sub": f"{ACCOUNT}.{USER}",
    "iat": now,
    "exp": now + 3600,
}

private_key_pem = private_key.private_bytes(
    encoding=serialization.Encoding.PEM,
    format=serialization.PrivateFormat.PKCS8,
    encryption_algorithm=serialization.NoEncryption()
)

jwt_token = jwt.encode(payload, private_key_pem, algorithm="RS256")

token_url = f"https://{ACCOUNT}.snowflakecomputing.com/polaris/api/catalog/v1/oauth/tokens"
response = requests.post(
    token_url,
    headers={"Content-Type": "application/x-www-form-urlencoded"},
    data={
        "grant_type": "client_credentials",
        "scope": f"session:role:{ROLE}",
        "client_secret": jwt_token
    }
)

if response.status_code == 200:
    token_data = response.json()
    access_token = token_data.get("access_token", "")
    with open("/tmp/horizon_access_token.txt", "w") as f:
        f.write(access_token)
    print(access_token)
')), stdout = TRUE)
    ACCESS_TOKEN <- trimws(readLines(token_file, n = 1))
}

# Try to attach the Iceberg catalog
# Note: DuckDB iceberg extension uses bearer token directly
cat("=== Attempting to attach Iceberg catalog ===\n")

# Method 1: Using ATTACH with bearer token
attach_sql <- sprintf("
ATTACH '%s' AS horizon (
    TYPE ICEBERG,
    ENDPOINT '%s',
    TOKEN '%s',
    WAREHOUSE '%s'
)", DATABASE, CATALOG_ENDPOINT, ACCESS_TOKEN, DATABASE)

tryCatch({
    cat("Attempting ATTACH with TOKEN...\n")
    dbExecute(con, attach_sql)
    cat("Catalog attached successfully!\n\n")
    
    # List available tables
    cat("=== Listing tables in horizon catalog ===\n")
    tables <- dbGetQuery(con, "SHOW TABLES IN horizon")
    print(tables)
    
}, error = function(e) {
    cat("ATTACH method failed:", conditionMessage(e), "\n\n")
    
    # Method 2: Try using OAuth2 parameters
    cat("Trying OAuth2 method...\n")
    attach_oauth_sql <- sprintf("
ATTACH '%s' AS horizon (
    TYPE ICEBERG,
    ENDPOINT '%s',
    OAUTH2_SERVER_URI '%s/v1/oauth/tokens',
    CLIENT_ID '%s',
    CLIENT_SECRET '%s',
    OAUTH2_SCOPE 'session:role:%s'
)", DATABASE, CATALOG_ENDPOINT, CATALOG_ENDPOINT, "service", ACCESS_TOKEN, ROLE)
    
    tryCatch({
        dbExecute(con, attach_oauth_sql)
        cat("OAuth2 catalog attached successfully!\n")
    }, error = function(e2) {
        cat("OAuth2 method also failed:", conditionMessage(e2), "\n\n")
        
        # Method 3: Direct Parquet reading via vended credentials
        # This requires getting the S3 credentials from loadTable response
        cat("=== Attempting direct Iceberg table read ===\n")
        cat("Note: This may require additional S3 credentials setup\n")
    })
})

# Cleanup
dbDisconnect(con, shutdown = TRUE)
cat("\n=== Test complete ===\n")
